#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

from bridge_io import read_extxyz

ATOMIC_MASS = {
    "H": 1.008, "He": 4.002602, "Li": 6.94, "Be": 9.0121831, "B": 10.81,
    "C": 12.011, "N": 14.007, "O": 15.999, "F": 18.998403163, "Ne": 20.1797,
    "Na": 22.98976928, "Mg": 24.305, "Al": 26.9815385, "Si": 28.085, "P": 30.973761998,
    "S": 32.06, "Cl": 35.45, "Ar": 39.948, "K": 39.0983, "Ca": 40.078,
    "Ti": 47.867, "V": 50.9415, "Cr": 51.9961, "Mn": 54.938044, "Fe": 55.845,
    "Co": 58.933194, "Ni": 58.6934, "Cu": 63.546, "Zn": 65.38,
}


def _type_map(symbols: list[str]) -> dict[str, int]:
    return {s: i + 1 for i, s in enumerate(sorted(set(symbols)))}


def _lattice_to_box(lat: list[list[float]]) -> tuple[float, float, float, float, float, float]:
    a, b, c = lat
    ax, ay, az = a
    bx, by, bz = b
    cx, cy, cz = c
    if abs(ay) > 1e-8 or abs(az) > 1e-8 or abs(bz) > 1e-8:
        raise SystemExit("Lattice must be prism-compatible: a=(ax,0,0), b=(xy,by,0), c=(xz,yz,cz)")
    if ax <= 0 or by <= 0 or cz <= 0:
        raise SystemExit("Invalid lattice lengths for LAMMPS prism")
    return ax, by, cz, bx, cx, cy


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--in-extxyz", required=True)
    ap.add_argument("--out-data", required=True)
    ap.add_argument("--frame", type=int, default=0)
    ap.add_argument("--type-map-out", default="type_map.json")
    ap.add_argument("--mass-map", default="")
    args = ap.parse_args()

    frames = read_extxyz(args.in_extxyz)
    fr = frames[args.frame]
    tmap = _type_map(fr.symbols)

    mass = dict(ATOMIC_MASS)
    if args.mass_map:
        mass.update({k: float(v) for k, v in json.loads(Path(args.mass_map).read_text()).items()})
    for sym in tmap:
        if sym not in mass:
            raise SystemExit(f"Missing mass for {sym}; provide --mass-map")

    xhi, yhi, zhi, xy, xz, yz = _lattice_to_box(fr.lattice)

    inv = {v: k for k, v in tmap.items()}
    out = [
        "# generated by convert_tdep_extxyz_to_lammps.py",
        "",
        f"{len(fr.symbols)} atoms",
        f"{len(tmap)} atom types",
        "",
        f"0.0 {xhi:.16g} xlo xhi",
        f"0.0 {yhi:.16g} ylo yhi",
        f"0.0 {zhi:.16g} zlo zhi",
        f"{xy:.16g} {xz:.16g} {yz:.16g} xy xz yz",
        "",
        "Masses",
        "",
    ]
    for tid in sorted(inv):
        sym = inv[tid]
        out.append(f"{tid} {mass[sym]:.16g} # {sym}")
    out.extend(["", "Atoms", ""])
    for i, (sym, (x, y, z)) in enumerate(zip(fr.symbols, fr.positions), start=1):
        out.append(f"{i} {tmap[sym]} {x:.16g} {y:.16g} {z:.16g}")

    Path(args.out_data).write_text("\n".join(out) + "\n", encoding="utf-8")
    Path(args.type_map_out).write_text(json.dumps(tmap, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"Wrote {args.out_data}")
    print(f"Wrote {args.type_map_out}")


if __name__ == "__main__":
    main()
